version: 1
author: Sebastian Döll <sebastian@andersnormal.us>
project: Kandinsky
tasks:
  test:
    disable: true
    desc: test
    vars:
      region:
        - test
    cmds:
      - go test -v ./...
  build:
    default: true
    deps:
      - test
    vars:
      region:
        - test
    cmds:
      - go build
      